name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_ADMIN }}
        password: ${{ secrets.ADMIN_PASSWORD }}
        script: |
          cd ${{ secrets.REPO_NAME }}
          git pull origin main
          docker compose -f docker-compose-redis.yml up --build -d